// This file is used by Cloudflare Pages with the @astrojs/cloudflare adapter
// It's automatically generated by the Astro build process
// You shouldn't need to modify this file manually

export { default as default } from "../dist/server/entry.mjs"; 