import type { Database } from "./db/database.types";

/**
 * Entity Type alias for flashcards derived from the database model.
 * This references the underlying flashcards row definition.
 */
export type FlashcardEntity = Database["public"]["Tables"]["flashcards"]["Row"];

/**
 * Entity Type alias for collections derived from the database model.
 */
export type CollectionEntity = Database["public"]["Tables"]["collections"]["Row"];

/**
 * DTO for representing a flashcard in API responses.
 * Maps DB 'front_content' to 'front_text' and DB 'back_content' to 'back_text'.
 * 'is_ai' is a derived flag (true if 'created_by' is not 'MAN').
 */
export interface FlashcardDTO {
  id: FlashcardEntity["id"];
  front_text: FlashcardEntity["front_content"];
  back_text: FlashcardEntity["back_content"];
  is_ai: boolean; // Derived from flashcardEntity.created_by (true if created_by !== 'MAN')
  created_at: FlashcardEntity["created_at"];
  collection_id: FlashcardEntity["collection_id"];
  collection_name?: string; // For display purposes
}

/**
 * DTO for pagination parameters in list endpoints.
 */
export interface PaginationDTO {
  page: number;
  limit: number;
  total: number;
}

/**
 * Response DTO for fetching flashcards.
 */
export interface GetFlashcardsResponseDTO {
  flashcards: FlashcardDTO[];
  pagination: PaginationDTO;
}

/**
 * Command Model for creating a new flashcard.
 * Uses the same text types as in the database entity.
 */
export interface CreateFlashcardCommand {
  front_text: FlashcardEntity["front_content"];
  back_text: FlashcardEntity["back_content"];
  collection_id?: string | null;
}

/**
 * Response DTO returned after creating a flashcard.
 */
export interface CreateFlashcardResponseDTO {
  message: string;
  flashcard: FlashcardDTO;
}

/**
 * Command Model for updating an existing flashcard.
 */
export interface UpdateFlashcardCommand {
  front_text: string;
  back_text: string;
}

/**
 * Response DTO returned after updating a flashcard.
 */
export interface UpdateFlashcardResponseDTO {
  message: string;
  flashcard: FlashcardDTO;
}

/**
 * Response DTO returned after deleting a flashcard.
 */
export interface DeleteFlashcardResponseDTO {
  message: string;
}

/**
 * Command Model for generating flashcards via an AI service.
 */
export interface GenerateFlashcardCommand {
  source_text: string;
  front_language?: string; // Language of the input text (front of card)
  back_language?: string;  // Language of the translation (back of card)
  collection_id?: string | null; // Optional collection to save generated flashcards to
}

/**
 * DTO for an individual flashcard candidate generated by AI.
 */
export interface FlashcardCandidateDTO {
  candidate_id: string;
  front_text: string;
  back_text: string;
  status: "pending" | "accepted" | "edited";
}

/**
 * Response DTO for AI-driven flashcard generation.
 */
export interface GenerateFlashcardResponseDTO {
  generation_id: string;
  candidates: FlashcardCandidateDTO[];
}

/**
 * Command Model for updating a generated flashcard candidate.
 * 'accept' indicates whether the candidate is accepted (true) or rejected (false).
 */
export interface UpdateFlashcardCandidateCommand {
  front_text: string;
  back_text: string;
}

/**
 * Response DTO returned after updating a flashcard candidate.
 */
export interface UpdateFlashcardCandidateResponseDTO {
  message: string;
  candidate: {
    candidate_id: string;
    front_text: string;
    back_text: string;
  };
}

/**
 * Response DTO returned after completing the AI flashcard generation review.
 */
export interface CompleteGenerationResponseDTO {
  message: string;
  stats: {
    total_candidates: number;
    accepted: number;
    rejected: number;
  };
  saved_flashcards: FlashcardDTO[];
}

/**
 * DTO for representing a collection in API responses.
 */
export interface CollectionDTO {
  id: CollectionEntity["id"];
  name: CollectionEntity["name"];
  created_at: CollectionEntity["created_at"];
}

/**
 * DTO for collection statistics including mastery indicators.
 */
export interface CollectionStatsDTO {
  total_cards: number;
  due_cards: number;
  avg_ease_factor: number;
  mastery_color: "red" | "yellow" | "green" | "gray";
}

/**
 * DTO combining collection info with statistics.
 */
export interface CollectionWithStatsDTO extends CollectionDTO {
  stats: CollectionStatsDTO;
}

/**
 * Command Model for creating a new collection.
 */
export interface CreateCollectionCommand {
  name: string;
}

/**
 * Response DTO returned after creating a collection.
 */
export interface CreateCollectionResponseDTO {
  message: string;
  collection: CollectionDTO;
}

/**
 * Command Model for updating a collection.
 */
export interface UpdateCollectionCommand {
  name: string;
}

/**
 * Response DTO returned after updating a collection.
 */
export interface UpdateCollectionResponseDTO {
  message: string;
  collection: CollectionDTO;
}

/**
 * Response DTO returned after deleting a collection.
 */
export interface DeleteCollectionResponseDTO {
  message: string;
}

/**
 * Response DTO for listing collections with stats.
 */
export interface GetCollectionsResponseDTO {
  collections: CollectionWithStatsDTO[];
}
